### ISSUE TITLE
leancloud.NewClient

### ISSUE THREAD

**Issue by zhixuan666** [leancloud/go-sdk#25]
```go
	client := leancloud.NewClient(&leancloud.ClientOptions{
		AppID:     "********",
		AppKey:    "*******",
		MasterKey: "*******",
		ServerURL: "*****.api.lncldglobal.com",
	})
```
返回 panic: please set API's serverURL for China region or legacy app

**Comment by soasurs** [comment]
你好，SDK 内部的云函数部分会使用 `NewEnvClient` 初始化一个用于调用云函数的 `client`，请设置相关的环境变量 `LEANCLOUD_APP_ID` `LEANCLOUD_APP_KEY` `LEANCLOUD_APP_MASTER_KEY` `LEANCLOUD_API_SERVER`。

建议您在调试使用 Go SDK 的项目时，使用 [lean-cli](https://github.com/leancloud/lean-cli) 工具，它会自动设置所有的环境变量，并且启动应用。

**Comment by stt106** [comment]
> 你好，SDK 内部的云函数部分会使用 `NewEnvClient` 初始化一个用于调用云函数的 `client`，请设置相关的环境变量 `LEANCLOUD_APP_ID` `LEANCLOUD_APP_KEY` `LEANCLOUD_APP_MASTER_KEY` `LEANCLOUD_API_SERVER`。
> 
> 建议您在调试使用 Go SDK 的项目时，使用 [lean-cli](https://github.com/leancloud/lean-cli) 工具，它会自动设置所有的环境变量，并且启动应用。

我使用了lean-cli，但是还有相同的错误。lean-cli启动时自是自动生成了current_app_id 和current_group两个变量， 不知道是不是和这个有关系。
我是第一次用lean-cli，但是lean-cli确实是启动了，我只是想用LC的数据库，为啥go sdk不支持手动设置环境变量呢？

**Comment by soasurs** [comment]
> 为啥go sdk不支持手动设置环境变量呢？

`lean-cli` 的 `lean up` 只是替代手动设置环境变量，如果希望手动设置环境变量，也是可以的。

@stt106
