### ISSUE TITLE
client 对象无法带着用户Session 发送请求

### ISSUE THREAD

**Issue by shiweifu** [leancloud/go-sdk#26]
Todo 中的对象，设置了 ACL，经测试使用 REST API 调用，可以正确返回数据：

```
curl -X GET \
  -H "X-LC-Id: " \
  -H "X-LC-Key:" \
  -H "X-LC-Session:" \
  -H "Content-Type: application/json" \
  https://BASE_URL/1.1/classes/Todo
```

在云函数中，使用 go sdk 进行调用则返回空（如果把ACL放开，则此时可以返回数据）：

```
func fetchItems(req *leancloud.FunctionRequest) (interface{}, error) {
	client := leancloud.NewEnvClient()

        // 此时 user 可以正确返回当前用户
	user, err :=  client.Users.Become(req.SessionToken)
	if err != nil {
		panic(err)
	}

	results := make([]Todo, 0)

        //
	if err := client.Class("Todo").NewQuery().Find(&results); err != nil {
		fmt.Println(err.Error())
		panic(err)
	}
	fmt.Println(results)
	return results, nil
}

```

另外，Go SDK 中类似其他 SDK 的 client.currentUser 啥时候加上啊，方便调试。

**Comment by soasurs** [comment]
你好，`Find` 方法有第二个参数 `authOptions`，类型为 [AuthOption](https://pkg.go.dev/github.com/leancloud/go-sdk/leancloud#AuthOption)，作用就是在向后端请求时带上特定的鉴权信息，比如 `masterKey`/`sessionToken` 等。如果希望在查询时能够指定 `masterKey`/`sessionToken`/`User` 请在后面传入 `UseMasterKey(key)`/`UseSessionToken(token)`/`UseUser(user)`。

具体请见 https://pkg.go.dev/github.com/leancloud/go-sdk/leancloud#Query.Find

**Comment by shiweifu** [comment]
OK，请问什么时候会用到 client.Users.Become 方法？现在需要本地记录 sessionToken，在每次请求都手动带上么？

**Comment by soasurs** [comment]
你好，Go 的 SDK 设计之初我们就不计划提供类似 `currentUser` 这样的特性，我们希望对于每个操作的权限能够更加精细的控制。

对于需要使用 `Session` 的情况，例如用户登录，在 `Login` 之后返回的 `User` 对象可以直接使用 `UseUser(user)` 传入，我们认为还是可以接受的。

`Become` 的目的只是单纯的将 `sessionToken` 换成 `User` 对象。

**Comment by shiweifu** [comment]
好的，谢谢回复，已经可以正确查询啦
