### ISSUE TITLE
如何绑定、使用第三方平台账号？

### ISSUE THREAD

**Issue by shiweifu** [leancloud/go-sdk#28]
看了一下文档，其他语言都是通过 `leancloud.User#loginWithAuthData` 方法来支持第三方账号绑定和登录的，但 Go SDK 并没有这个方法，请问在 Go SDK 中如何实现第三方账号的绑定和登录？

**Comment by soasurs** [comment]
`authData` 部分在 Go SDK 的当前版本中暂未实现，主要原因是，`authData` 一般在客户端(Web/iOS/Android)上使用较多，服务端主要还是使用云引擎部分和基础的存储功能。后续版本会增加对于 `authData` 的支持。

**Comment by shiweifu** [comment]
好的，通过 REST API 糊了一个，以后 SDK 有了再更新～
