### ISSUE TITLE
Panic issues with reflecting when querying data

### ISSUE THREAD

**Issue by jeffguorg** [leancloud/go-sdk#29]
Golang Version: 1.16.3
Package Version: 0.1.0

# Problem 1

Code Snippet: 
```golang
type Counter struct {
	leancloud.Object

	// ....

	Counter uint64
}
var (
	counter = Counter{
		Counter: 1,
	}
)
if err := query.First(&counter); err != nil {
	http.Error(w, err.Error(), http.StatusInternalServerError)
	return
}
```

It did not panic, but embedded `Object` is not filled with data.

I dive in the sdk and traced the code. find that when you [bind data into the struct](https://github.com/leancloud/go-sdk/blob/master/leancloud/encoding.go#L387), it iterate through the fields like `Object`, `Counter` and other fields I set, but it directly jumped over `Object` and did not fill data into it.

# Problem 2

And I tried to use leancloudObject to query objectId. something like this:
```golang
var (
	counterObj leancloud.Object
)
if err := query.First(&counterObj); err != nil {
	http.Error(w, err.Error(), http.StatusInternalServerError)
	return
}
```
the code panic. the bind method was trying to set createdAt field, which is string type, to `CreatedAt time.Time`, and it lead to the panic. I think there is more issues like this in sdk.

for now I'm going to use Python or Node to build apps, but I'm looking forward to the moment this could fix

**Comment by soasurs** [comment]
Thank you for the feedback, we have reproduced the problem and will start fixing it ASAP.
